name: Unit Tests

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  test:
    name: Run All Lambda Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # --- TEST 1: LOGIN HANDLER ---
      - name: Install Login Dependencies
        run: npm ci
        working-directory: ./src/backend/LambdaLoginHandler

      - name: Run Login Tests
        run: npm test
        working-directory: ./src/backend/LambdaLoginHandler

      # --- TEST 2: REGISTER HANDLER ---
      - name: Install Register Dependencies
        run: npm ci
        working-directory: ./src/backend/LambdaRegisterHandler

      - name: Run Register Tests
        run: npm test
        working-directory: ./src/backend/LambdaRegisterHandler
